/**
 * Whether a released version has to be installed, or merely offered.
 *
 * Kept away from the updater plugin on purpose: deciding what an update means
 * is a rule, and a rule that can only be exercised by installing a real signed
 * bundle is a rule nobody can test.
 */

/** What the update endpoint said about the newest release. */
export interface UpdateOffer {
  version: string;
  /** The release notes, which is also where a hard floor is declared. */
  notes: string;
}

export type UpdateVerdict =
  | { status: "none" }
  /** Worth having, dismissible, and the app stays usable either way. */
  | { status: "optional"; version: string }
  /** The running version is below the floor the release declared. */
  | { status: "required"; version: string; minimum: string };

/**
 * The line a release adds to say "everything older than this is finished".
 *
 * A marker in the release notes rather than a field of its own: `latest.json`
 * is generated by the build and has no room for extra keys, and the notes are
 * the one part of a release the publisher writes by hand at exactly the moment
 * they know whether the change breaks anything.
 */
const MINIMUM_MARKER = /^[ \t]*min-supported-version:[ \t]*v?([0-9]+(?:\.[0-9]+)*)/im;

/**
 * `-1`, `0` or `1`, comparing release numbers segment by segment.
 *
 * Missing segments count as zero, so `1.2` and `1.2.0` are the same version.
 * Anything after a `-` is dropped: a pre-release sorts with the release it is
 * a pre-release of, which is close enough for deciding whether to offer an
 * update and avoids an entire semver implementation.
 */
export function compareVersions(a: string, b: string): number {
  const parts = (v: string) =>
    v
      .trim()
      .replace(/^v/, "")
      .split("-")[0]!
      .split(".")
      .map((n) => Number.parseInt(n, 10) || 0);

  const left = parts(a);
  const right = parts(b);
  const length = Math.max(left.length, right.length);

  for (let i = 0; i < length; i += 1) {
    const diff = (left[i] ?? 0) - (right[i] ?? 0);
    if (diff !== 0) return diff < 0 ? -1 : 1;
  }
  return 0;
}

/** The floor a release declared, or `null` when it declared none. */
export function readMinimumSupported(notes: string): string | null {
  return MINIMUM_MARKER.exec(notes)?.[1] ?? null;
}

/**
 * What to do about `offer`, given the version that is running.
 *
 * The floor is read from the newest release rather than tracked separately,
 * which means a user several versions behind still learns about a break that
 * was declared in a release they skipped.
 */
export function evaluateUpdate(
  currentVersion: string,
  offer: UpdateOffer | null,
): UpdateVerdict {
  if (!offer) return { status: "none" };
  if (compareVersions(offer.version, currentVersion) <= 0) return { status: "none" };

  const minimum = readMinimumSupported(offer.notes);
  // A floor above the release announcing it would lock out everyone forever,
  // including whoever installs the new version, so it is ignored as a typo.
  if (
    minimum &&
    compareVersions(currentVersion, minimum) < 0 &&
    compareVersions(minimum, offer.version) <= 0
  ) {
    return { status: "required", version: offer.version, minimum };
  }
  return { status: "optional", version: offer.version };
}
